---
# cluster_name is used to group the nodes in a folder within VirtualBox:
cluster_name: Kubernetes Cluster
network:
  dns_servers:
    - 8.8.8.8
    - 1.1.1.1
  pod_cidr: 10.244.0.0/16
  service_cidr: 10.96.0.0/12
nodes:
  control:
    cpu: 2
    memory: 4096
  workers:
    count: 1
    cpu: 2
    memory: 4096
software:
  box: bento/ubuntu-22.04
  calico: 3.28.2
  # dashboard: 2.7.0
  dashboard: 
  kubernetes: v1.31
  os: xUbuntu_22.04
  crio: v1.30