---
cluster_name: Kubernetes Cluster
environment: development
network:
  dns_servers:
    - 1.1.1.1
    - 9.9.9.9
  pod_cidr: 10.244.0.0/16
  service_cidr: 10.96.0.0/12
nodes:
  control:
    cpu: 2
    memory: 6144
    ip: 192.168.100.10
  workers:
    count: 2
    cpu: 2
    memory: 6144
    ip_start: 192.168.100.20
software:
  box: bento/ubuntu-24.04
  calico: 3.28.2
  dashboard: 
  kubernetes: v1.34
  os: xUbuntu_22.04
  crio: v1.35
shared_folders: []
